export const TYPE_MAPING = {
    "AE": "Munition ship",
    "AR": "Repair ship",
    "BB": "Battleship",
    "BBV": "Aviation Battleship",
    "BC": "Battlecruiser",
    "BM": "Monitor",
    "CA": "Heavy Cruiser",
    "CB": "Large Cruiser",
    "CL": "Light Cruiser",
    "CV": "Aircraft Carrier",
    "CVL": "Light Aircraft Carrier",
    "DD": "Destroyer",
    "DDG": "Guided-missile Destroyer",
    "IX(M)": "Decisive",
    "IX(S)": "Elite",
    "IX(V)": "Super Rare",
    "SS": "Submarine",
    "SSV": "Submarine Aircraft Carrier",
}