import Link from "next/link";
import Head from "next/head";

export default function FourOhFour() {
  return (
    <>
      <Head>
        <title>404 Not Found</title>
        <meta name="description" content="404 Page" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`duration-500 bg-[#0D1829] bg-opacity-90 mx-auto w-[90vw] lg:max-w-[calc(100vw-30px)] lg:w-[calc(100vw-30px)] lg:mx-[15px]}
                 h-[100%] overflow-y-scroll rounded-2xl p-[5px] md:p-[10px] lg:p-[15px]`}>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
        555
        <br></br>
      </div>
    </>
  );
}
